[project]
name = "aerial-library"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "robo4you" }
]
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "appdirs>=1.4.4",
    "cflib>=0.1.30",
]
